### ISSUE TITLE
Element create errors out when toggling quickly 

### ISSUE THREAD

**Issue by Rahul147** [andrewdacenko/web-components-angular-react#1]
When toggling between angular and react, element create errors out.

**Comment by andrewdacenko** [comment]
@Rahul147 in examples provided there is 50% probability of application to fail. This is done for demo purpose to show how errors can be thrown from component to shell.

I'll add description to README.

**Comment by Rahul147** [comment]
Sorry should have seen that. Do you mind if I add a toggle that says show error handling, when selected will result in the 50% error or it will work normally/smoothly?

**Comment by andrewdacenko** [comment]
@Rahul147 sure, i'd appreciate!
